//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S3G11_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProducedIn
    {
        public Nullable<int> ProducedInID { get; set; }
        public int WorkCenterID { get; set; }
        public int ProductID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual WorkCenter WorkCenter { get; set; }
    }
}
