//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S3G11_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salesperson
    {
        public int SalespersonID { get; set; }
        public string SalespersonName { get; set; }
        public string SalespersonTelephone { get; set; }
        public string SalespersonFax { get; set; }
        public Nullable<int> TerritoryID { get; set; }
    
        public virtual SalesTerritory SalesTerritory { get; set; }
    }
}
